spring.application.name=casa-de-deus-api

# CONFIGURAÇÃO DO NEON POSTGRESQL
# Substitua o link abaixo pela sua Connection String do Neon (deixe o jdbc:postgresql:// no começo)
spring.datasource.url=jdbc:postgresql://ep-frosty-queen-ackgpjj5-pooler.sa-east-1.aws.neon.tech/neondb?sslmode=require
spring.datasource.username=neondb_owner
spring.datasource.password=npg_x9auOLvH2yFd

# HIBERNATE (Vai criar as tabelas automaticamente)
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

# Configuração da Porta
server.port=8080
